update init scripts

diff --git a/SD_ROOT/wz_mini/etc/network.d/S01wlanhw b/SD_ROOT/wz_mini/etc/network.d/S01wlanhw
--- a/SD_ROOT/wz_mini/etc/network.d/S01wlanhw
+++ b/SD_ROOT/wz_mini/etc/network.d/S01wlanhw
@@ -1,14 +1,25 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:
+# Short-Description: WLAN HW Init check
+# Description:       Make sure the WLAN hardware is functional and initialized before proceeding.
+### END INIT INFO
 
-#Wait for wlan hardware to be intitialized in app_init.sh, this must be blocking.
+. /opt/wz_mini/etc/rc.common
 
-while true; do
-	if ifconfig wlan0 | grep "HWaddr"; then
-		echo "wlan0 hwaddr is up"
-		break
-	else
-		echo "wlan0 hwaddr not ready yet..."
-	        sleep 5
-	fi
-done
+case "$1" in
+	start)
+		echo "#####$(basename "$0")#####"
+
+		#Wait for wlan hardware to be intitialized in app_init.sh, this must be blocking.
+		#Lets come up with a solution for some cameras with failed wlan hw, someone on reddit mentioned it"
+		echo "Waiting for wlan hw init"
+
+		wait_for_wlan $(basename "$0")
+		;;
+	*)
+		echo "Usage: $0 {start}"
+		exit 1
+		;;
+esac
 
